// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcrprbtaxtfmjfbhsahc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjcnByYnRheHRmbWpmYmhzYWhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NTA0OTIsImV4cCI6MjA1MTEyNjQ5Mn0.8Jmn5wRgO5Z5BC0St7AnqSM_xdYLOowMXLtVPewvnxg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);